#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : appstream-glib
Version  : 0.7.16
Release  : 16
URL      : https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.7.16.tar.xz
Source0  : https://people.freedesktop.org/~hughsient/appstream-glib/releases/appstream-glib-0.7.16.tar.xz
Summary  : Objects and methods for reading and writing AppStream metadata
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: appstream-glib-bin = %{version}-%{release}
Requires: appstream-glib-data = %{version}-%{release}
Requires: appstream-glib-lib = %{version}-%{release}
Requires: appstream-glib-license = %{version}-%{release}
Requires: appstream-glib-locales = %{version}-%{release}
Requires: appstream-glib-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : buildreq-qmake
BuildRequires : docbook-xml
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gperf
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libgcab-1.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(uuid)
BuildRequires : util-linux

%description
AppStream-Glib
==============
This library provides GObjects and helper methods to make it easy to read and
write AppStream metadata. It also provides a simple DOM implementation that
makes it easy to edit nodes and convert to and from the standardized XML
representation. It also supports reading of Debian-style DEP-11 metadata.

%package bin
Summary: bin components for the appstream-glib package.
Group: Binaries
Requires: appstream-glib-data = %{version}-%{release}
Requires: appstream-glib-license = %{version}-%{release}

%description bin
bin components for the appstream-glib package.


%package data
Summary: data components for the appstream-glib package.
Group: Data

%description data
data components for the appstream-glib package.


%package dev
Summary: dev components for the appstream-glib package.
Group: Development
Requires: appstream-glib-lib = %{version}-%{release}
Requires: appstream-glib-bin = %{version}-%{release}
Requires: appstream-glib-data = %{version}-%{release}
Provides: appstream-glib-devel = %{version}-%{release}
Requires: appstream-glib = %{version}-%{release}
Requires: appstream-glib = %{version}-%{release}

%description dev
dev components for the appstream-glib package.


%package lib
Summary: lib components for the appstream-glib package.
Group: Libraries
Requires: appstream-glib-data = %{version}-%{release}
Requires: appstream-glib-license = %{version}-%{release}

%description lib
lib components for the appstream-glib package.


%package license
Summary: license components for the appstream-glib package.
Group: Default

%description license
license components for the appstream-glib package.


%package locales
Summary: locales components for the appstream-glib package.
Group: Default

%description locales
locales components for the appstream-glib package.


%package man
Summary: man components for the appstream-glib package.
Group: Default

%description man
man components for the appstream-glib package.


%prep
%setup -q -n appstream-glib-0.7.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571580683
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Ddep11=false -Dstemmer=false -Drpm=false  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/appstream-glib
cp %{_builddir}/appstream-glib-0.7.16/COPYING %{buildroot}/usr/share/package-licenses/appstream-glib/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/appstream-glib-0.7.16/data/tests/rpmbuild-font/COPYING %{buildroot}/usr/share/package-licenses/appstream-glib/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang appstream-glib

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/appstream-builder
/usr/bin/appstream-compose
/usr/bin/appstream-util

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/AppStreamGlib-1.0.typelib
/usr/share/bash-completion/completions/appstream-builder
/usr/share/bash-completion/completions/appstream-util
/usr/share/gettext/its/appdata.its
/usr/share/gettext/its/appdata.loc
/usr/share/gir-1.0/*.gir
/usr/share/installed-tests/appstream-glib/appdata-validate.test
/usr/share/installed-tests/appstream-glib/destdir-check.test

%files dev
%defattr(-,root,root,-)
/usr/include/libappstream-glib/appstream-glib.h
/usr/include/libappstream-glib/as-agreement-section.h
/usr/include/libappstream-glib/as-agreement.h
/usr/include/libappstream-glib/as-app-builder.h
/usr/include/libappstream-glib/as-app.h
/usr/include/libappstream-glib/as-bundle.h
/usr/include/libappstream-glib/as-checksum.h
/usr/include/libappstream-glib/as-content-rating.h
/usr/include/libappstream-glib/as-enums.h
/usr/include/libappstream-glib/as-format.h
/usr/include/libappstream-glib/as-icon.h
/usr/include/libappstream-glib/as-image.h
/usr/include/libappstream-glib/as-inf.h
/usr/include/libappstream-glib/as-launchable.h
/usr/include/libappstream-glib/as-markup.h
/usr/include/libappstream-glib/as-monitor.h
/usr/include/libappstream-glib/as-node.h
/usr/include/libappstream-glib/as-problem.h
/usr/include/libappstream-glib/as-profile.h
/usr/include/libappstream-glib/as-provide.h
/usr/include/libappstream-glib/as-release.h
/usr/include/libappstream-glib/as-require.h
/usr/include/libappstream-glib/as-review.h
/usr/include/libappstream-glib/as-screenshot.h
/usr/include/libappstream-glib/as-store.h
/usr/include/libappstream-glib/as-suggest.h
/usr/include/libappstream-glib/as-tag.h
/usr/include/libappstream-glib/as-translation.h
/usr/include/libappstream-glib/as-utils.h
/usr/include/libappstream-glib/as-version.h
/usr/lib64/libappstream-glib.so
/usr/lib64/pkgconfig/appstream-glib.pc
/usr/share/aclocal/*.m4

%files lib
%defattr(-,root,root,-)
/usr/lib64/asb-plugins-5/libasb_plugin_appdata.so
/usr/lib64/asb-plugins-5/libasb_plugin_desktop.so
/usr/lib64/asb-plugins-5/libasb_plugin_font.so
/usr/lib64/asb-plugins-5/libasb_plugin_gettext.so
/usr/lib64/asb-plugins-5/libasb_plugin_hardcoded.so
/usr/lib64/asb-plugins-5/libasb_plugin_icon.so
/usr/lib64/asb-plugins-5/libasb_plugin_shell_extension.so
/usr/lib64/libappstream-glib.so.8
/usr/lib64/libappstream-glib.so.8.0.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/appstream-glib/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/appstream-glib/06877624ea5c77efe3b7e39b0f909eda6e25a4ec

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/appstream-builder.1
/usr/share/man/man1/appstream-compose.1
/usr/share/man/man1/appstream-util.1

%files locales -f appstream-glib.lang
%defattr(-,root,root,-)

